Style/Documentation:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - ╲
    - ╱

Metrics/LineLength:
  Max: 120

Style/AndOr:
  EnforcedStyle: conditionals

Layout/EmptyLineAfterGuardClause:
  Enabled: false
